SELECT USER FROM DUAL;
SELECT SYS_CONTEXT('USERENV','INSTANCE_NAME') FROM DUAL;
SHOW CON_NAME;


CREATE TABLE CUSTOMERS
(
ID NUMBER(10) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
LOCATION_ID NUMBER(10) NOT NULL,
CONSTRAINT CUSTOMERS_PK PRIMARY KEY(ID),
CONSTRAINT CUSTOMERS_FK FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(ID)
);

CREATE TABLE LOCATIONS
(
ID NUMBER(10) NOT NULL,
STREET VARCHAR2(50) NOT NULL,
CITY VARCHAR2(50) NOT NULL,
PINCODE NUMBER(6) NOT NULL,
CONSTRAINT LOCATIONS_PK PRIMARY KEY(ID)
);

DROP TABLE CUSTOMERS;
